name: Create Storage

on:
  issue_comment:
    types: [created, deleted]


jobs:
  create_storage_job:
    runs-on: ubuntu-latest
    name: Create storage
    steps:
    - name: Create storage
      uses: MichalBednarz/storage-action@master
      with:
        user-key: ${{ secrets.GITHUB_TOKEN }}
