on:
   issue_comment:
     types: [deleted, created]

jobs:
  create_repo_job:
    runs-on: ubuntu-latest
    name: Fetch review comments
    steps:
      - name: Create storage repo
        run: |
          curl --request POST \
          --url https://api.github.com/user/repos \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "name": "contextbuddy-storage",
            "private": "true"
            }'

