on:
   issue_comment:
     types: [created, deleted]

jobs:
  generate_snapshot_job:
    runs-on: ubuntu-latest
    name: Generate and save snapshot
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Create temporary file with review comments
      uses: MichalBednarz/contextbuddy@gh-actions
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Git config # required by sbt generateSnapshot
      run: |
        git config --global user.email "context@buddy.com"
        git config --global user.name "ContextBuddy"
    - name: Download previous snapshot
      uses: actions/download-artifact@v1.0.0
      with:
         name: contextbuddy-snapshot
         path: /home/runner/.contextbuddy
    - name: Generate snapshot
      run: sbt generateSnapshot
    - name: Upload generated snapshot
      uses: actions/upload-artifact@v1.0.0
      with:
        name: contextbuddy-snapshot
        path: /home/runner/.contextbuddy
