on:
  issue_comment:
    types: [created, deleted]

jobs:
  generate_snapshot_job:
    runs-on: ubuntu-latest
    name: Generate snapshot job
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2 # does clean option remove file?
    - name: Create temporary file with review comments
      uses: MichalBednarz/sample-action@master 
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Git config
      run: |
        git config --global user.email "you@example.com"
        git config --global user.name "CB"
    - name: Generate snapshot
      run: sbt generateSnapshot
    - name: Save snapshot in storage branch
      run: |
        git checkout --orphan contextbuddy/storage
        git rm -rf .
        mv /home/runner/.contextbuddy/sbt-action/storage/snapshots /home/runner/work/sbt-action/sbt-action
        git status
#     - name: asdf
#       run: |
        
#         cd /home/runner/.contextbuddy/sbt-action/storage/snapshots/src/main/scala/Main.scala/Tokens
#         cat tokens.txt
#         cat positions.txt
#     - name: Save snapshot to storage repo
#       uses: MichalBednarz/sample-action@save-storage
#       with:
#         repo-token: ${{ secrets.GITHUB_TOKEN }}
#         storage-token: ${{ secrets.STORAGE_SECRET }} # storage repository personal access token  
