on:
  issue_comment:
    types: [created, deleted]

jobs:
  generate_snapshot_job:
    runs-on: ubuntu-latest
    name: Generate snapshot job
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2 # does clean option remove file?
    - name: Create temporary file with review comments
      uses: MichalBednarz/sample-action@master 
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Git config
      run: |
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"
    - name: Generate snapshot
      run: sbt generateSnapshot
    - name: asdf
      run: |
        cd /home/runner/work/sbt-action/sbt-action
        tree
    - name: Save snapshot to storage repo
      uses: MichalBednarz/sample-action@save-storage
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        storage-token: ${{ secrets.STORAGE_SECRET }} # storage repository personal access token  
