on:
  issue_comment:
    types: [created, deleted]

jobs:
  sbt_job:
    runs-on: ubuntu-latest
    name: sbt job
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2 # does clean option remove file?
    - name: Create temporary file with review comments
      uses: MichalBednarz/sample-action@master
    - name: Dispatch save event to storage
      uses: MichalBednarz/sample-action@save-storage
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
#    - run: sbt generateSnapshot
