name: ContextBuddy CI

on:
 push:
  branches: 
   - master
#  pull_request:
#   types: [closed]
#  issue_comment:
#   types: [created]
jobs:
  generate_snapshot_job:
    runs-on: ubuntu-latest
    name: Generate and save snapshot
    steps:
    - name: Set env
      run: | 
       echo ::set-env name=OWNER::$(echo "${GITHUB_REPOSITORY/\/*/}")
       echo ::set-env name=REPO::$(echo "${GITHUB_REPOSITORY/*\//}") # can env be accessed within js action?
    - name: Create storage if not present # if present REPO_EXISTED env variable will be set to true
      id: create-storage
      uses: MichalBednarz/storage-action@master
      with:
       user-key: ${{ secrets.STORAGE_SECRET }} 
       owner: ${{ env.OWNER }}
       repo: ${{ env.REPO }}
    - name: Checkout storage repository
      uses: actions/checkout@v2
      with: 
       repository: ${{ env.OWNER }}/contextbuddy-storage
       token: ${{ secrets.STORAGE_SECRET }}
    - name: test
      run: echo ${{ steps.create-storage.outputs.repo-existed}}
    - name: Copy storage
      if: steps.create-storage.outputs.repo-existed == 'true'
      run: cp -r ${{ env.REPO }}/.contextbuddy ~/.
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Cache SBT
      uses: actions/cache@v1.1.2
      with:
        path: ~/.sbt
        key: sbt-${{ runner.os }}-${{ hashFiles('**/*.sbt') }}
    - name: Cache SBT ivy cache
      uses: actions/cache@v1.1.2
      with:
        path: ~/.ivy2/cache
        key: sbt-ivy-${{ runner.os }}-${{ hashFiles('**/*.sbt') }}
    - name: Create temporary file with review comments
      uses: MichalBednarz/contextbuddy@gh-actions
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Git config # required by sbt generateSnapshot
      run: |
        git config --global user.email "context@buddy.com"
        git config --global user.name "ContextBuddy"
    - name: Generate snapshot
      run: sbt generateSnapshot
    - name: Checkout storage repository
      uses: actions/checkout@v2
      with: 
       repository: ${{ env.OWNER }}/contextbuddy-storage
       token: ${{ secrets.STORAGE_SECRET }}
    - name: Save snapshot to storage
      run: | 
       cp -rf ~/.contextbuddy/$REPO ./
       git add .
       git commit -m 'Update snapshot'
       git push -ff
