on:
   pull_request:
     types: [closed]

jobs:
  sbt_cache_job:
    runs-on: ubuntu-latest
    name: Cache sbt
    steps:
       - name: Checkout repository
         uses: actions/checkout@v2         
       - name: test
         run: echo $GITHUB_WORKSPACE/.sbt
       - name: Git config # required by sbt generateSnapshot
         run: |
          git config --global user.email "context@buddy.com"
          git config --global user.name "ContextBuddy"
       - name: Cache SBT ivy cache
         id: cache-ivy
         uses: actions/cache@v1.1.2
         with:
             path: /home/runner/work/sbt-action/sbt-action/ivy2/cache
             key: ${{ runner.os }}-sbt-ivy-cache-${{ hashFiles('**/*.sbt') }}
       - name: Cache hit
         if: steps.cache-ivy.outputs.cache-hit != 'true'
         run: echo "cache hit false"
       - name: Cache SBT
         uses: actions/cache@v1.1.2
         with:
             path: /home/runner/work/sbt-action/sbt-action/sbt
             key: ${{ runner.os }}-sbt-${{ hashFiles('**/*.sbt') }}
       - name: Log
         run: |
            ls -a $GITHUB_WORKSPACE
       - name: Run sbt
         run: | 
           cd /home/runner/work/sbt-action/sbt-action
           sbt -Dsbt.ivy.home=/home/runner/work/sbt-action/sbt-action/ivy2 -Dsbt.boot.directory=/home/runner/work/sbt-action/sbt-action/sbt/boot generateSnapshot
       - name: Log
         run: |
            ls -a $GITHUB_WORKSPACE
