on:
   pull_request:
     types: [closed]

jobs:
  sbt_cache_job:
    runs-on: ubuntu-latest
    name: Cache sbt
    steps:
       - name: Checkout repository
         uses: actions/checkout@v2         
       - name: test
         run: echo $GITHUB_WORKSPACE/.sbt
       - name: Git config # required by sbt generateSnapshot
         run: |
          git config --global user.email "context@buddy.com"
          git config --global user.name "ContextBuddy"
       - name: Cache SBT ivy cache
         uses: actions/cache@v1
         with:
             path: $GITHUB_WORKSPACE/.ivy2/cache
             key: ${{ runner.os }}-sbt-ivy-cache-${{ hashFiles('**/*.sbt') }}
       - name: Cache SBT
         uses: actions/cache@v1
         with:
             path: $GITHUB_WORKSPACE/.sbt
             key: ${{ runner.os }}-sbt-${{ hashFiles('**/*.sbt') }}
       - name: Log
         run: |
            ls -a $GITHUB_WORSPACE
       - name: Run sbt
         run: sbt -Dsbt.ivy.home=$GITHUB_WORKSPACE/.ivy2 -Dsbt.boot.directory=$GITHUB_WORKSPACE/.sbt/boot generateSnapshot
       - name: Log
         run: |
            ls -a $GITHUB_WORKSPACE
