on:
   pull_request:
     branches: 
        - master

jobs:
  sbt_cache_job:
    runs-on: ubuntu-latest
    name: Cache sbt
    steps:
       - name: Checkout repository
         uses: actions/checkout@v2         
       - name: test
         run: echo $GITHUB_WORKSPACE/.sbt
       - name: Git config # required by sbt generateSnapshot
         run: |
          git config --global user.email "context@buddy.com"
          git config --global user.name "ContextBuddy"
       - name: Cache SBT
         id: cache-sbt
         uses: actions/cache@v1.1.0
         with:
             path: ~/.sbt
             key: ${{ runner.os }}-sbt-${{ hashFiles('**/*.sbt') }}
       - name: Cache SBT ivy cache
         id: cache-ivy
         uses: actions/cache@v1.1.0
         with:
             path: ~/.ivy2/cache
             key: ${{ runner.os }}-sbt-ivy-cache-${{ hashFiles('**/*.sbt') }}
       - name: Generate snapshot
         run: sbt generateSnapshot
       - name: Cache hit
         if: steps.cache-ivy.outputs.cache-hit != 'true'
         run: echo "cache hit false"
       - name: Cache sbt hit
         if: steps.cache-sbt.outputs.cache-hit != 'true'
         run: echo "cache hit false"
