on:
   pull_request:
     types: [closed]

jobs:
  sbt_cache_job:
    runs-on: ubuntu-latest
    name: Cache sbt
    steps:
       - name: Checkout repository
         uses: actions/checkout@v2         
       - name: Git config # required by sbt generateSnapshot
         run: |
          git config --global user.email "context@buddy.com"
          git config --global user.name "ContextBuddy"
       - name: Cache SBT
         uses: actions/cache@v1.1.2
         with:
           path: /home/runner/.sbt
           key: sbt-${{ matrix.os }}-${{ hashFiles('**/*.sbt') }}
       - name: Cache SBT ivy cache
         uses: actions/cache@v1.1.2
         with:
           path: /home/runner/.ivy2/cache
           key: sbt-ivy-${{ matrix.os }}-${{ hashFiles('**/*.sbt') }}
       - name: Log
         run: |
            ls -a /home/runner/
       - name: Run sbt
         run: sbt generateSnapshot
       - name: Log
         run: |
            ls /home/runner/.ivy2/cache
            ls /home/runner/.sbt
